fullnameOverride: veritable-ui
invitationPin:
  secret: blah
cloudagent:
  enabled: false
externalCloudagent:
  host: "veritable-cloudagent-admin.default.svc.cluster.local"
  port: "3000"
emailTransport: SMTP_EMAIL
smtpCredentials:
  enabled: true
  userSecret: smtp-user
  passwordSecret: smtp-password
